tasks/task/urls.py
from django.urls import path

from task import views
from graphene_django.views import GraphQLView
from task.schema import schema
urlpatterns = [
    path('',views.home),
    path('graphql', GraphQLView.as_view(graphiql=True, schema=schema)),
]

tasks/tasks/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('task.urls'))
]

tasks/task/models.py
from django.db import models

# Create your models here.
class task(models.Model):
    cat_list = (("university","university"),("School","School"),("Home","Home"))
    description = models.CharField(max_length=100)
    category = models.CharField(choices=cat_list,max_length=15)
    date = models.DateField()

    def __str__(self):
        return self.description

tasks/task/forms.py
from django import forms

from task.models import task


class taskForm(forms.ModelForm):
    class Meta:
        model = task
        fields = ('__all__')

tasks/task/views.py
from django.shortcuts import render
from task.forms import taskForm
from task.models import task


def home(request):
    if request.POST.get('delete'):
        tasks = task.objects.all()
        form = taskForm()
        task.objects.filter(id__in=request.POST.getlist('inputs')).delete()
        context = {
            'tasks':tasks,
            'form':form
        }
    elif request.method == 'POST':
        tasks = task.objects.all()
        form = taskForm(request.POST)
        if form.is_valid():
            form.save()
        context = {
            'tasks': tasks,
            'form': form
        }
    else:
        tasks = task.objects.all()
        form = taskForm()
        context = {
            'tasks': tasks,
            'form':form,
        }
    return render(request,'home.html',context)

tasks/task/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>Task Manager</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrapmin.css' %}">
    <link rel="stylesheet" href="{% static 'css/gijgo.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
</head>
<body>

<section class="form">
    <h1>Add New Task</h1>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}

        <button class="danger" type="submit"><i class="fas fa-plus"></i>Add task</button>
    </form>

</section>

<section class="tasks">


<ul>
<form method="post">{% csrf_token %}
<button class="danger" type="submit" name="delete" value="Delete Task"><i class="far fa-trash-alt"></i>Delete tasks</button>
    <br><br><br><br><br>
    <h1>Task List</h1>
    {% for tasks in tasks %}
     <li>
    <div class="task-box">

<input type="checkbox" name="inputs" id="option{{input.id}}" value={{tasks.id}} />
        {{tasks.description}} , {{tasks.category}} <i class="far fa-calendar-alt"></i> <strong>{{tasks.date}}</strong>

            <input type="hidden" name="t" value="{{tasks.id}}">



    </div> </li>
    {% endfor %}
 </form>
</ul>
</section>
<script src="{% static 'js/jquery-min.js' %}"></script>
<script src="{% static 'js/gijgo.min.js' %}"></script>
<script>
        $('#id_date').datepicker(
            { uiLibrary: 'bootstrap4', modal: true }
        );
    </script>
</body>
</html>